package com.flansmod.client.model;

public enum EnumAnimationType {

    NONE("NONE", 0), BOTTOM_CLIP("BOTTOM_CLIP", 1), PISTOL_CLIP("PISTOL_CLIP", 2), TOP_CLIP("TOP_CLIP", 3),
    SIDE_CLIP("SIDE_CLIP", 4), P90("P90", 5), SHOTGUN("SHOTGUN", 6), RIFLE("RIFLE", 7), REVOLVER("REVOLVER", 8),
    REVOLVER2("REVOLVER2", 9), END_LOADED("END_LOADED", 10), RIFLE_TOP("RIFLE_TOP", 11), BULLPUP("BULLPUP", 12),
    ALT_PISTOL_CLIP("ALT_PISTOL_CLIP", 13), GENERIC("GENERIC", 14), BACK_LOADED("BACK_LOADED", 15),
    STRIKER("STRIKER", 16), BREAK_ACTION("BREAK_ACTION", 17), CUSTOM("CUSTOM", 18);

    // $FF: synthetic field
    private static final EnumAnimationType[] $VALUES = new EnumAnimationType[]{NONE, BOTTOM_CLIP, PISTOL_CLIP,
            TOP_CLIP, SIDE_CLIP, P90, SHOTGUN, RIFLE, REVOLVER, REVOLVER2, END_LOADED, RIFLE_TOP, BULLPUP,
            ALT_PISTOL_CLIP, GENERIC, BACK_LOADED, STRIKER, BREAK_ACTION, CUSTOM};

    EnumAnimationType(String var1, int var2) {
    }

}
